<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="RACIT061" failures="1" tests="9" name="Regression tests" time="0.123" errors="0" timestamp="2024-12-31T20:20:14 IST">
  <testcase classname="testng_tests.Day3" name="mobileloginHomeLoan" time="0.007"/>
  <testcase classname="testng_tests.Day3" name="webfunctionHomeLoan" time="0.001"/>
  <testcase classname="testng_tests.Day3" name="weblogoutHomeLoan" time="0.002"/>
  <testcase classname="testng_tests.Day4" name="apiloginCarLoan" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng_tests.Day4.apiloginCarLoan(Day4.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- apiloginCarLoan -->
  <testcase classname="testng_tests.Day4" name="mobileloginCarLoan" time="0.001"/>
  <testcase classname="testng_tests.Day4" name="webloginCarLoan" time="0.003"/>
  <testcase classname="testng_tests.Day4" name="webloginCarLoan" time="0.001"/>
  <testcase classname="testng_tests.Day4" name="webloginCarLoan" time="0.002"/>
  <testcase classname="testng_tests.Day3" name="apiloginHomeLoan" time="0.001"/>
  <testcase classname="testng_tests.Day3" name="webloginHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- webloginHomeLoan -->
</testsuite> <!-- Regression tests -->
